### PR TITLE
Actually use SSL.

### PR DESCRIPTION
**Pull request by errietta**

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
oh shit! That's bad if this never worked!  Let me double check that the property didn't change from one version of b2g to another (some do!).  That way this doesn't break older clients.  We'll have to remember to pull this update into irc.  Great sleuthing!

**Comment by nickdesaulniers** [comment]
according to @asutherland (maintainer of gaia/email), this property changed over the lifetime of Gaia.  We can safely pass both options (old and new), that way we don't break old clients that are stuck.

@errietta , can you update the patch to include bother, rather than remove the old property?

**Comment by nickdesaulniers** [comment]
Looks like it changed from 1.0.1, to 1.1.  Is Firesea really that old? https://bugzilla.mozilla.org/show_bug.cgi?id=784816

**Comment by errietta** [comment]
@nickdesaulniers  there we go ;)

**Comment by nickdesaulniers** [comment]
nice, let's update the git submodule in firesea too

**Pull request merged**
